---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "myapplication.com"
    http:
      paths:
      - pathType: Prefix
        path: "/myapp"
        backend:
          service:
            name: myapp
            port:
              number: 80
